name: kn_fit_api
description: A web server built using the shelf package.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dart_jsonwebtoken: ^2.4.1
  dotenv: ^3.0.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  logger: ^1.1.0
  mysql1: ^0.19.2
  shelf: ^1.1.0
  shelf_router: ^1.1.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  lints: ^1.0.1
  pedantic: ^1.10.0
  shelf_router_generator: ^1.0.2
