openapi: 3.0.0
info:
  description: "API KN Fit"
  version: "1.0.0"
  title: "Swagger KN Fit"
servers:
  - url: http://localhost:8080
    description: Remote server
tags:
- name: "student"
  description: "Access to Student"

paths:
  /student:
    post:
      tags:
        - student
      summary: Create student
      description: This can only be done by the logged in student.
      operationId: createStudent
      requestBody:
        description: Created student object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
            

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
        studentName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
        phone:
          type: string
        studentStatus:
          type: integer
          format: int32
          description: Student Status
      